rootProject.name = "my_web"
include("websocket_client")
include("websocket_server")
include("websocket_client2")
include("test")
include("http_test")
include("hot_swap_common")
include("hot_swap_web_test")
include("hot_swap_test")
include("listener_test")
